site_name: Computação Embarcada - 2.0

theme:
  name: active-handout-theme

docs_dir: content
site_dir: docs

#site_url: https://insper-education.github.io/active-handout/
#repo_name: "Embarcados"
#repo_url: https://github.com/insper-education/active-handout
#edit_uri: edit/main/content/

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - include-markdown
  - glightbox
  - termynal
  - active-handout:
      telemetry: false
      plugin_exercise_counter: false
      backend_url: https://example-backend.com.br/api/
      course_slug: Active Handout Example 2022
      tag_tree:
        - reference:
            - choice-exercise
            - parsons-exercise
            - text-exercise
        - grandparent-tag:
            - parent-tag:
                - child-tag

extra:
  custom_variables:
    rules_cppcheck_classroom: https://classroom.github.com/a/FU5oUkNZ
    rules_variables_classroom: https://classroom.github.com/a/sXx8vWcl
    rules_isr_classroom: https://classroom.github.com/a/9ZP6ial1
    rules_isr_volatile_classroom: https://classroom.github.com/a/5RQM6NE4
    rules_head_classroom: https://classroom.github.com/a/2m6a9oth

    aula_1_mural: https://app.mural.co/t/elementos9119/m/elementos9119/1708285630708/f7182e10dd73d346d8a1e216545399fffbf036f4?sender=ub569a9273c6e285461187641

    lab_gpio_pre_classroom: https://classroom.github.com/a/Og2WhTSP
    lab_gpio_pre_deadline:  Antes da próxima aula - 14/9 ou 15/9
    lab_gpio_pra_classroom: https://classroom.github.com/a/QnfriADY
    lab_gpio_pra_deadline: 19/8 (Antes da aula)
    lab_irq_pre_classroom: https://classroom.github.com/a/GYW_HTi4
    lab_irq_pre_deadline: 19/8 (Antes da aula)
    lab_irq_pra_classroom: https://classroom.github.com/a/BvJWdDWJ
    lab_irq_pra_deadline: 26/8 (Antes da aula)

    lab_timer_pre_classroom: https://classroom.github.com/a/XOv7V1gR
    lab_timer_pre_deadline: 09/9 (Antes da aula)
    lab_timer_pra_classroom: https://classroom.github.com/a/C9JbpHMx
    lab_timer_pra_deadline: 09/9 (Antes da aula)

    lab_rtos_pre_classroom: https://classroom.github.com/a/q2759a2m
    lab_rtos_pre_deadline: 16/9 (Antes da aula)
    lab_rtos_pra_classroom: https://classroom.github.com/a/AzDUsFIa
    lab_rtos_pra_deadline: 16/9 (Antes da aula)

    lab_adc_pwm_pre_classroom: https://classroom.github.com/a/Q9mObLot
    lab_adc_pwm_pre_deadline: (23/9) (Antes da aula)
    lab_adc_pwm_pra_classroom: https://classroom.github.com/a/l5wJ-rbQ
    lab_adc_pwm_pra_deadline: (23/9) (Antes da aula)

    lab_i2c_pre_classroom:
    lab_i2c_pre_deadline:
    lab_i2c_pra_classroom:
    lab_i2c_pra_deadline:

    lab_expert_1_classroom:
    lab_expert_1_deadline:
    
    lab_expert_2_classroom:
    lab_expert_2_deadline:

    aps_1_classroom: https://classroom.github.com/a/G1_ZsJG4
    aps_1_deadline: 30/08 (Sexta)
    aps_1_forms: https://forms.gle/Ybg4zvc29i1NJpMs8

    aps_2_deadline: TBD
    aps_2_mural: https://app.mural.co/t/elementos9119/m/elementos9119/1710349957892/a51ad9d7ba35bb72689454f3caf839f45bf46044?sender=ub569a9273c6e285461187641
    aps_2_classroom: https://classroom.github.com/a/m89YrzNI


markdown_extensions:
  - footnotes
  - markdown.extensions.admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - attr_list
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: content
      check_paths: true

nav:
  - Home: index.md
  - Aulas: aulas.md
  - Avaliação: avaliacao.md
  - Infra:
    - Linux ou Mac: infra-linux-docker.md
    - Windows: infra-windows.md
  - Prototipando:
    - Fabricação: prototipos/prototipos.md
    - Entradas: prototipos/entradas.md
    - Saídas: prototipos/saida.md
  - Utils:
      Uinput: utils/utils-uinput.md
      pyautogui: utils/utils-pyautogui.md
      vjoy: utils/utils-vjoy.md
      Volume: utils/utils-volume.md
  - Dispositivos:
      - Buzzer: dispositivos/buzzer.md
      - "HC-SR04": https://perrobotica.fandom.com/pt-br/wiki/Sensor_de_dist%C3%A2ncia_Hcsr04
      - OLED1: dispositivos/oled1.md
      - Servomotor: dispositivos/servo.md
      - Análogicos: dispositivos/analogicos.md
  - Pico W:
      - Datasheet: https://datasheets.raspberrypi.com/picow/pico-w-datasheet.pdf
      - Hardware: https://www.raspberrypi.com/documentation/microcontrollers/images/picow-pinout.svg
      - pico-examples: pico/pico-examples.md
      - Programando: pico/pico-debugging.md
      - WIFI: pico/pico-wifi.md
  - RP2040:
      - Datasheet: https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf
      - SDK: https://www.raspberrypi.com/documentation/pico-sdk/index_doxygen.html
#      - Code snippets: rp2040/rp2040-snippets.md
      - Delay: rp2040/rp2040-delay.md
      - GPIO: rp2040/rp2040-gpio.md
      - GPIO IRQ: rp2040/rp2040-gpio-irq.md
      - Timer: rp2040/rp2040-timer.md
      - RTC: rp2040/rp2040-rtc.md
      - Flash: https://kevinboone.me/picoflash.html
      - ADC: rp2040/rp2040-adc.md
      - PWM: rp2040/rp2040-pwm.md
      - I2C: rp2040/rp2040-i2c.md
      - DMA: rp2040/rp2040-dma.md
      - UART: rp2040/rp2040-uart.md
  - FreeRTOS:
      - RTOS: freertos/freertos-basic.md
      - Tasks: freertos/freertos-tasks.md
      - VtaskDelay: freertos/freertos-vtaskDelay.md
      - Software Timer: freertos/freertos-software-time.md
      - Semaphore: freertos/freertos-semaphore.md
      - Queue: freertos/freertos-queue.md
      - Queue struct: freertos/freertos-queue-advanced.md
      - SMP: freertos/freertos-smp.md
  - Code quality:
      - Visão geral: CodeQuality/topview.md
      - Regras: CodeQuality/rules.md
      - Cppcheck: CodeQuality/cppcheck.md
      - Variáveis: CodeQuality/variables.md
      - ISR - variáveis: CodeQuality/isr-variables.md
      - ISR - handler: CodeQuality/isr-handler.md
      - Head File: CodeQuality/head-file.md
      - RTOS: CodeQuality/rtos.md
  - Labs core:
      - Preparatórios: labs/pre-lab.md
      - Prática: labs/pra-lab.md
      - GPIO:
        - ⏰ Qualidade de Código: labs/qualidade-codigo-1
        - ⏰ Preparatório: labs/gpio-pre-lab.md
        - Prática: labs/gpio-pra-lab.md
      - ISR:
        - ⏰ Qualidade de Código: labs/qualidade-codigo-irs
        - ⏰ Preparatório: labs/irq-pre-lab.md
        - Prática: labs/irq-pra-lab.md
      - Timer:
        - ⏰ Preparatório: labs/timer-pre-lab.md
        -  Prática: labs/timer-pra-lab.md
      - RTOS:
        - ⏰ Preparatório: labs/rtos-pre-lab.md
        - Prática: labs/rtos-pra-lab.md
      - ADC/PWM:
       - Preparatório: labs/adc-pwm-pre-lab.md
       - Prática: labs/adc-pwm-pra-lab.md
#      - I2C:
#        - Preparatório: labs/i2c-pre-lab.md
#        - Prática: labs/i2c-pra-lab.md
#  - Labs experts:
#      - Sobre: labs-expert/labs-expert-about.md
#      - Comunicação:
#          - WIFI: labs-expert/labs-expert-com-wifi.md
#          - Bluetooth: labs-expert/labs-expert-com-bt.md
#      - DSP:
#          - Áudio: labs-expert/labs-expert-dsp-audio.md
#          - IA: labs-expert/labs-expert-dsp-ia.md
#      - Sensores/Atuadores:
#          - Servomotor: labs-expert/labs-expert-sensors-servomotor.md
#          - LCD / BME280: labs-expert/labs-expert-sensors-bme280-ili9341.md
#      - Firmware:
#          - Driver: labs-expert/labs-expert-firmware-driver.md
#          - DMA: labs-expert/labs-expert-firmware-dma.md

  - APS:
    - aps/aps-1-genius.md
    - aps/aps-2-controle.md
