site_name: Computação Embarcada - 2.0

theme:
  name: active-handout-theme

docs_dir: content
site_dir: docs

#site_url: https://insper-education.github.io/active-handout/
#repo_name: "Embarcados"
#repo_url: https://github.com/insper-education/active-handout
#edit_uri: edit/main/content/

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - include-markdown
  - glightbox
  - termynal
  - active-handout:
      telemetry: false
      plugin_exercise_counter: false
      backend_url: https://example-backend.com.br/api/
      course_slug: Active Handout Example 2022
      tag_tree:
        - reference:
            - choice-exercise
            - parsons-exercise
            - text-exercise
        - grandparent-tag:
            - parent-tag:
                - child-tag

extra:
  custom_variables:
    rules_cppcheck_classroom: https://classroom.github.com/a/mT5GPk_E
    rules_variables_classroom: https://classroom.github.com/a/4dedv4p8
    rules_head_classroom: https://classroom.github.com/a/sQPQYgXq
    rules_isr_volatile_classroom: https://classroom.github.com/a/MIZb0nXB
    rules_isr_classroom: https://classroom.github.com/a/Xpvuvr8r

    aula_1_mural: https://app.mural.co/t/elementos9119/m/elementos9119/1708285630708/f7182e10dd73d346d8a1e216545399fffbf036f4?sender=ub569a9273c6e285461187641

    lab_gpio_pre_classroom: https://classroom.github.com/a/t40wWocH
    lab_gpio_pre_deadline: 21/2 ou 22/2 (Antes da próxima aula)
    lab_gpio_pra_classroom: https://classroom.github.com/a/RVDWvMjq
    lab_gpio_pra_deadline: 26/2 (Antes da aula)
    lab_irq_pre_classroom: https://classroom.github.com/a/ZSB_DhzL
    lab_irq_pre_deadline: 26/2 (Antes da aula)
    lab_irq_pra_classroom: https://classroom.github.com/a/oNT1nEiP
    lab_irq_pra_deadline: 04/2 (Antes da aula)

    lab_timer_pre_classroom: https://classroom.github.com/a/KEhvSnZw
    lab_timer_pre_deadline: 04/2 (Antes da aula)
    lab_timer_pra_classroom: https://classroom.github.com/a/RyzMEcIl
    lab_timer_pra_deadline: 11/03

    lab_rtos_pre_classroom: https://classroom.github.com/a/1VfPSxZx
    lab_rtos_pre_deadline: 12/03 - 23h59
    lab_rtos_pra_classroom: https://classroom.github.com/a/AIMxAvtD
    lab_rtos_pra_deadline: 18/03 (Antes da aula)

    lab_adc_pwm_pre_classroom: https://classroom.github.com/a/B4Uh531U
    lab_adc_pwm_pre_deadline: 21/03 - 23h59
    lab_adc_pwm_pra_classroom: https://classroom.github.com/a/vzIo0hHz
    lab_adc_pwm_pra_deadline: 08/04 (Antes da aula)


    lab_i2c_pre_classroom: https://classroom.github.com/a/vYUH2R0h
    lab_i2c_pre_deadline: 15/05 (Antes da aula)
    lab_i2c_pra_classroom: https://classroom.github.com/a/LHH9EXB0
    lab_i2c_pra_deadline: 15/04 (Antes da aula)

    aps_1_classroom: https://classroom.github.com/a/niP2yPR9
    aps_1_deadline: Segunda 11/03 - 13h30
    aps_1_forms: https://forms.gle/bM6MVGDT8vLV4Ch87

    aps_2_deadline: Segunda 12/04 - Sexta
    aps_2_classroom: https://classroom.github.com/a/2cyfcwx3


markdown_extensions:
  - footnotes
  - markdown.extensions.admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - attr_list
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: content
      check_paths: true

nav:
  - Home: index.md
  - Aulas: aulas.md
  - Avaliação: avaliacao.md
  - Infra: infra-linux-docker.md
  - Prototipando:
    - Fabricação: prototipos/prototipos.md
    - Entradas: prototipos/entradas.md
    - Saídas: prototipos/saida.md
  - Utils:
      Uinput: utils/utils-uinput
      Uinput: utils/utils-vjoy
  - Dispositivos:
      - dispositivos/buzzer.md
      - "HC-SR04": https://perrobotica.fandom.com/pt-br/wiki/Sensor_de_dist%C3%A2ncia_Hcsr04
      - OLED1: dispositivos/oled1.md
  - Pico W:
      - Datasheet: https://datasheets.raspberrypi.com/picow/pico-w-datasheet.pdf
      - Hardware: https://www.raspberrypi.com/documentation/microcontrollers/images/picow-pinout.svg
      - pico-examples: https://github.com/raspberrypi/pico-examples
      - Programando: pico/pico-debugging.md

        #      - Code snippets: pico/pico-snippets.md
  - RP2040:
      - Datasheet: https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf
      - SDK: https://www.raspberrypi.com/documentation/pico-sdk/index_doxygen.html
#      - Code snippets: rp2040/rp2040-snippets.md
      - Delay: rp2040/rp2040-delay.md
      - GPIO: rp2040/rp2040-gpio.md
      - GPIO IRQ: rp2040/rp2040-gpio-irq.md
      - Timer: rp2040/rp2040-timer.md
      - RTC: rp2040/rp2040-rtc.md
      - Flash: https://kevinboone.me/picoflash.html
      - ADC: rp2040/rp2040-adc.md
      - PWM: rp2040/rp2040-pwm.md
      - I2C: rp2040/rp2040-i2c.md
      - DMA: rp2040/rp2040-dma.md
      - UART: rp2040/rp2040-uart.md
  - FreeRTOS:
      - RTOS: freertos/freertos-basic.md
      - Tasks: freertos/freertos-tasks.md
      - VtaskDelay: freertos/freertos-vtaskDelay.md
      - Software Timer: freertos/freertos-software-time.md
      - Semaphore: freertos/freertos-semaphore.md
      - Queue: freertos/freertos-queue.md
      - Queue struct: freertos/freertos-queue-advanced.md
  - Code quality:
      - Visão geral: CodeQuality/topview.md
      - Regras: CodeQuality/rules.md
      - Cppcheck: CodeQuality/cppcheck.md
      - Variáveis: CodeQuality/variables.md
      - ISR - variáveis: CodeQuality/isr-variables.md
      - ISR - handler: CodeQuality/isr-handler.md
      - Head File: CodeQuality/head-file.md
      - RTOS: CodeQuality/rtos.md
  - Labs:
      - Preparatórios: labs/pre-lab.md
      - Prática: labs/pra-lab.md
      - GPIO:
        - Preparatório: labs/gpio-pre-lab.md
        - Prática: labs/gpio-pra-lab.md
      - IRQ:
        - Preparatório: labs/irq-pre-lab.md
        - Prática: labs/irq-pra-lab.md
      - Timer:
        - Preparatório: labs/timer-pre-lab.md
        - Prática: labs/timer-pra-lab.md
      - RTOS:
        - Preparatório: labs/rtos-pre-lab.md
        - Prática: labs/rtos-pra-lab.md
      - ADC/PWM:
        - Preparatório: labs/adc-pwm-pre-lab.md
        - Prática: labs/adc-pwm-pra-lab.md
      - I2C:
        - Preparatório: labs/i2c-pre-lab.md
        - Prática: labs/i2c-pra-lab.md

  - APS:
      - aps/aps-1-genius.md
      - aps/aps-2-controle.md
